version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - aws cloudformation package --template ./template-app.yaml --s3-bucket ${ARTIFACT_STORE} --output-template-file packaged-template-app.yaml
artifacts:
  files:
    - packaged-template-app.yaml
  discard-paths: yes
